version: "3.7"
services:
  web_lifo_db_server:
    image: postgres
    restart: always
    env_file:
      - Environment.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
  web_lifo:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - web_lifo_db_server
    environment:
      PGHOST: web_lifo_db_server
    depends_on:
      - web_lifo_db_server
    hostname:
       web_lifo
    networks:
      - default
    ports:
      - "8765:8765"
    expose:
      - "8765"
volumes:
  data: